language: cpp

matrix:
  include:
    - os: osx
      compiler: clang

    - os: linux
      compiler: gcc
      env: COMPILER=g++-4.8
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.8

    - os: linux
      compiler: clang
      env: COMPILER=clang++-3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6

cache:
    apt: true
    ccache: true
    directories:
    - $HOME/.wheelhouse

before_install:
  - utils/travis-before-install-${TRAVIS_OS_NAME}.sh

install:
  - utils/travis-install-deps-${TRAVIS_OS_NAME}.sh

script:
  - utils/build-${TRAVIS_OS_NAME}.sh

after_success:
  - utils/after_build-${TRAVIS_OS_NAME}.sh

deploy:
  provider: releases
  api_key:
    secure: Vax27ifQsc8SlTsLYVbxVJANDAxDroegN6nOPXCN1MLaoh4W2DQ/iGGx+waIOSYig8Sh+AUz2JhCFuMLMVqwFoWY2rxNPBrxhTBjm3aDhylbB+mRECnbInNb0kS3qv4lNDN6lHD4B6K01FWUUiHX14s2JQx4ut+KuwMxxhxyO4Y=
  file: 'build/*.dmg'
  file_glob: true
  skip_cleanup: true
  on:
    condition: "$TRAVIS_OS_NAME = osx"
    tags: true
    all_branches: true
    repo: hluk/CopyQ
